
server:
  port: 8083
spring:
  datasource:
   url: jdbc:mysql://localhost:3306/activitystream_step1
   username: root
   password: root
  jpa:
    hibernate:
      ddl-auto: update
      
spring.jpa.properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect

      
